### ISSUE TITLE
GetTickersAsync failes for Binance

### ISSUE THREAD

**Issue by jacobdeboer33** [DigitalRuby/ExchangeSharp#789]
Hi there

I'm no longer able to execute GetTickersAsync for binance. it failes with the following exception:

2022-09-22 22:18:33,742  - Exception in run: System.IO.InvalidDataException: No market symbol metadata returned or unable to find symbol metadata for AXSBIDR
   at ExchangeSharp.ExchangeAPI.ExchangeMarketSymbolToCurrenciesAsync(String marketSymbol)
   at ExchangeSharp.ExchangeAPIExtensions.ParseTickerAsync(ExchangeAPI api, JToken token, String marketSymbol, Object askKey, Object bidKey, Object lastKey, Object baseVolumeKey, Object quoteVolumeKey, Object timestampKey, TimestampType timestampType, Object baseCurrencyKey, Object quoteCurrencyKey, Object idKey)
   at ExchangeSharp.BinanceGroup.BinanceGroupCommon.ParseTickerAsync(String symbol, JToken token)
   at ExchangeSharp.BinanceGroup.BinanceGroupCommon.OnGetTickersAsync()
   at ExchangeSharp.ExchangeAPI.<GetTickersAsync>b__85_0()
   at ExchangeSharp.CryptoUtility.<>c__DisplayClass89_0`1.<<CacheMethod>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at ExchangeSharp.MemoryCache.GetOrCreate[T](String key, Func`1 notFound)
   at ExchangeSharp.CryptoUtility.CacheMethod[T](ICache cache, Dictionary`2 methodCachePolicy, Func`1 method, Object[] arguments)
   at ExchangeSharp.ExchangeAPI.GetTickersAsync()

Any suggestions?

Thanks,
Jacob

**Comment by jacobdeboer33** [comment]
Hmmm. It seems to be working fine when I'm using a clone of the repo instead of the NuGet package. I will close the issue now.

Thanks,
Jacob

**Comment by vslee** [comment]
A new official nuget will be released soon. For now, you can try using the prerelease nugets: https://dev.azure.com/DigitalRuby/DigitalRuby/_artifacts/feed/DigitalRuby
Those are automatically kept up to date with the main branch of the repo.

**Comment by NicolasDorier** [comment]
Do you know when official nuget coming out?

**Comment by vslee** [comment]
Ok, I just released it https://github.com/DigitalRuby/ExchangeSharp/releases/tag/v1.0.3

**Comment by NicolasDorier** [comment]
@vslee should be reopened, doesn't work.

```
No market symbol metadata returned or unable to find symbol metadata for AXSBIDR
   at ExchangeSharp.ExchangeAPI.ExchangeMarketSymbolToCurrenciesAsync(String marketSymbol)
   at ExchangeSharp.ExchangeAPIExtensions.ParseTickerAsync(ExchangeAPI api, JToken token, String marketSymbol, Object askKey, Object bidKey, Object lastKey, Object baseVolumeKey, Object quoteVolumeKey, Object timestampKey, TimestampType timestampType, Object baseCurrencyKey, Object quoteCurrencyKey, Object idKey)
   at ExchangeSharp.BinanceGroup.BinanceGroupCommon.ParseTickerAsync(String symbol, JToken token)
   at ExchangeSharp.BinanceGroup.BinanceGroupCommon.OnGetTickersAsync()
   at ExchangeSharp.ExchangeAPI.<GetTickersAsync>b__85_0()
   at ExchangeSharp.CryptoUtility.<>c__DisplayClass89_0`1.<<CacheMethod>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at ExchangeSharp.MemoryCache.GetOrCreate[T](String key, Func`1 notFound)
   at ExchangeSharp.CryptoUtility.CacheMethod[T](ICache cache, Dictionary`2 methodCachePolicy, Func`1 method, Object[] arguments)
   at ExchangeSharp.ExchangeAPI.GetTickersAsync()
   at BTCPayServer.Services.Rates.ExchangeSharpRateProvider`1.GetRatesAsync(CancellationToken cancellationToken) in C:\Sources\btcpayserver\BTCPayServer.Rating\Providers\ExchangeSharpRateProvider.cs:line 28
   at BTCPayServer.Services.Rates.BackgroundFetcherRateProvider.Fetch(CancellationToken cancellationToken) in C:\Sources\btcpayserver\BTCPayServer.Rating\Providers\BackgroundFetcherRateProvider.cs:line 232
   at BTCPayServer.Services.Rates.BackgroundFetcherRateProvider.LatestFetch.GetResult() in C:\Sources\btcpayserver\BTCPayServer.Rating\Providers\BackgroundFetcherRateProvider.cs:line 72
   at BTCPayServer.Services.Rates.BackgroundFetcherRateProvider.Fetch(CancellationToken cancellationToken) in C:\Sources\btcpayserver\BTCPayServer.Rating\Providers\BackgroundFetcherRateProvider.cs:line 256
   at BTCPayServer.Services.Rates.BackgroundFetcherRateProvider.GetRatesAsync(CancellationToken cancellationToken) in C:\Sources\btcpayserver\BTCPayServer.Rating\Providers\BackgroundFetcherRateProvider.cs:line 205
```

**Comment by dennisreimann** [comment]
Can confirm, it still does not work with v1.0.3

**Comment by vslee** [comment]
Re-opened. We would welcome a pull request from anyone.

**Comment by BZ-CO** [comment]
It is the same issue as #785. Already fixed with #787.
Everything seems to be fine in the master branch.
I am not sure why it throws exception in the 1.0.3 nuget package.

**Comment by dennisreimann** [comment]
@vslee Can you double-check why this might not be included in the 1.0.3 release?

**Comment by vslee** [comment]
https://dev.azure.com/DigitalRuby/DigitalRuby/_artifacts/feed/DigitalRuby

**Comment by dennisreimann** [comment]
Narrowed down the problem: It seems like the binance.com API which is used in ExchangeSharp does not return the `BTCUSD` pair, whereas e.g. binance.us does:

- https://api.binance.com/api/v3/ticker/24hr?symbol=BTCUSD
- https://api.binance.us/api/v3/ticker/24hr?symbol=BTCUSD

I tried replacing the base URL (`.us` instead of `.com`) and that works for us. So the issue in general seems more like binance.com removed that trading pair.

**Comment by BZ-CO** [comment]
@dennisreimann There is no USD currency on BinanceCom

**Comment by BZ-CO** [comment]
I think we should close this issue.
